services:
  transcoder-rabbitmq:
    container_name: transcoder-rabbitmq
    image: rabbitmq:3.9.7-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 5s
      timeout: 30s
      retries: 5

  transcoder-redis:
    container_name: transcoder-redis
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  transcoder-api:
    container_name: transcoder-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - '5000:5000'
    depends_on:
      transcoder-redis:
        condition: service_started
      transcoder-rabbitmq:
        condition: service_healthy

  transcoder-downloader:
    container_name: transcoder-downloader
    build:
      context: .
      dockerfile: ./apps/downloader/Dockerfile
    environment:
      - NODE_ENV=development
    depends_on:
      transcoder-rabbitmq:
        condition: service_healthy
    volumes:
      - shared-storage:/shared

  transcoder-encoding-director:
    container_name: transcoder-encoding-director
    build:
      context: .
      dockerfile: ./apps/encoding-director/Dockerfile
    environment:
      - NODE_ENV=development
    depends_on:
      transcoder-rabbitmq:
        condition: service_healthy

  transcoder-encoder:
    container_name: transcoder-encoder
    build:
      context: .
      dockerfile: ./apps/encoder/Dockerfile
    environment:
      - NODE_ENV=development
    depends_on:
      transcoder-rabbitmq:
        condition: service_healthy
    volumes:
      - shared-storage:/shared

  transcoder-uploader:
    container_name: transcoder-uploader
    build:
      context: .
      dockerfile: ./apps/uploader/Dockerfile
    environment:
      - NODE_ENV=development
    depends_on:
      transcoder-rabbitmq:
        condition: service_healthy
    volumes:
      - shared-storage:/shared

volumes:
  shared-storage:
