services:
  transcoder-localstack:
    container_name: 'transcoder-localstack'
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      SERVICES: s3
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT: http://127.0.0.1:4566
      DEBUG: 1
      DOCKER_HOST: unix:///var/run/docker.sock
      DATA_DIR: /tmp/localstack/data
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

  transcoder-rabbitmq:
    container_name: 'transcoder-rabbitmq'
    image: rabbitmq:3.9.7-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - transcoder-network

  transcoder-redis:
    container_name: transcoder-redis
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

networks:
  transcoder-network:
    name: transcoder-network
    driver: bridge
